# Format: major.minor.micro
# No letters are allowed for META-INF compatibility.
version=${version}

# Same as "version" above, except that for nightly use "-SNAPSHOT" instead of ".5".  
mavenVersion=${version}

buildInfo=${maven.build.timestamp}